# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  project: '**/Blog.csproj'
  solution: '**/Blog.sln'
  testProject: '**/Blog.Test.csproj'

steps:

- task: NuGetCommand@2
  name: 'RestorePackages' 
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Restore .NET project'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    restoreArguments: '-r linux-x64'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'PublishProject'
  displayName: 'Publish .NET project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) -r linux-x64 --self-contained false --no-restore'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  name: 'Test'
  displayName: 'Test .NET project'
  inputs:
    command: test
    projects: '$(testProject)'
    arguments: '--configuration $(buildConfiguration)'

- task: CopyFiles@2
  name: 'CopyDockerFiles'
  displayName: 'Copy dockerfile'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'Dockerfile'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Blog'
    
- task: CopyFiles@2
  name: 'CopyKubernetesFiles'
  displayName: 'Copy kubernetes'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'deployment.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Blog'
    
    
- task: PublishBuildArtifacts@1
  name: 'PublishArtifacts'
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  


